version: '2'
services:
  web:
    image: dockercloud/hello-world
    labels:
      - "traefik.backend=web"
      - "traefik.frontend.rule=Host:web.example.com"
    networks:
      - back-tier

  traefik_lb:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - front-tier
      - back-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  ha_lb:
      image: dockercloud/haproxy
      ports:
        - 81:80
      links:
        - web
      networks:
        - front-tier
        - back-tier
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
