version: '2'
services:
  web:
    image: dockercloud/hello-world
    labels:
      - "traefik.backend=web"
      - "traefik.frontend.rule=Host:web.example.com"
    networks:
          - back-tier

  traefik_lb:
    image: traefik
    command: --web --docker --docker.domain=example.com --logLevel=DEBUG -c /dev/null --docker.endpoint=$DOCKER_HOST  --docker.tls --docker.tls.ca=/ssl/ca.pem --docker.tls.cert=/ssl/server.pem --docker.tls.key=/ssl/server-key.pem --docker.tls.insecureSkipVerify --docker.watch
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - back-tier
    volumes:
      - /var/lib/boot2docker/:/ssl

networks:
  back-tier:
    driver: overlay
